name: make linux

on:
  push:
    branches: [ "master","Dev0ke" ]
  pull_request:
    branches: [ "master","Dev0ke" ]
  release:
    types: [created,published] # 表示在创建新的 Release 时触发
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: gui
      run: cd gui/velociraptor/ && npm install
    - name: make gui
      run: cd gui/velociraptor/ && make build
    - name: make bin
      run: export PATH=/go/bin:$PATH && make linux


